spring.application.name=bea-bi-backend

# ===================== DATASOURCE ORACLE - DATA WAREHOUSE =====================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521:XE
# Alternative plus stable pour Oracle XE :
# spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XE

spring.datasource.username=grh_dw
spring.datasource.password=grh_dw
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===================== HIKARI CONNECTION POOL =====================
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.pool-name=DWH-HikariPool

# ===================== JPA / HIBERNATE =====================
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Lecture seule - Data Warehouse analytique
spring.jpa.properties.hibernate.connection.readOnly=true

# ===================== SERVEUR =====================
server.port=8081

# ===================== KEYCLOAK / OAUTH2 =====================
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8180/realms/bea-realm

# ===================== SWAGGER / OPENAPI =====================
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.oauth2-redirect-url=http://localhost:8081/swagger-ui/oauth2-redirect.html

springdoc.swagger-ui.oauth-client-id=bea-bi-client
springdoc.swagger-ui.oauth-use-pkce=false
springdoc.swagger-ui.disable-swagger-default-url=true
springdoc.swagger-ui.tags-sorter=alpha
springdoc.swagger-ui.operations-sorter=alpha

# ===================== ACTUATOR =====================
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# ===================== LOGGING =====================
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.com.bea=INFO